export const getRoomC335Schedule = () => {
  return [
    {
      class_day: "Luni",
      start_hour: 7,
      end_hour: 8,
      frequency: 0,
      formation: "MIE1",
      class_type: "Course",
      course_name: "MLE0021",
      professor: "Prof. Andreica Anca",
    },
    {
      class_day: "Joi",
      start_hour: 1,
      end_hour: 2,
      frequency: 0,
      formation: "IE3",
      class_type: "Course",
      course_name: "MLE5072",
      professor: "Lect. Ionescu Radu",
    },
    {
      class_day: "Joi",
      start_hour: 1,
      end_hour: 2,
      frequency: 0,
      formation: "I3",
      class_type: "Course",
      course_name: "MLE5072",
      professor: "Lect. Ionescu Radu",
    },
    {
      class_day: "Luni",
      start_hour: 5,
      end_hour: 6,
      frequency: 2,
      formation: "311",
      class_type: "Seminar",
      course_name: "MLR5006",
      professor: "Lect. Munteanu Bogdan",
    },
    {
      class_day: "Luni",
      start_hour: 5,
      end_hour: 6,
      frequency: 1,
      formation: "312",
      class_type: "Seminar",
      course_name: "MLR5006",
      professor: "Lect. Munteanu Bogdan",
    },
    {
      class_day: "Vineri",
      start_hour: 1,
      end_hour: 2,
      frequency: 1,
      formation: "236",
      class_type: "Seminar",
      course_name: "MLR5014",
      professor: "Prof. Vasilescu Mihai",
    },
    {
      class_day: "Vineri",
      start_hour: 1,
      end_hour: 2,
      frequency: 2,
      formation: "237",
      class_type: "Seminar",
      course_name: "MLR5014",
      professor: "Prof. Vasilescu Mihai",
    },
    {
      class_day: "Vineri",
      start_hour: 3,
      end_hour: 4,
      frequency: 0,
      formation: "IE3",
      class_type: "Course",
      course_name: "MLE5157",
      professor: "Lect. Filipescu Vasile",
    },
    {
      class_day: "Marți",
      start_hour: 11,
      end_hour: 12,
      frequency: 0,
      formation: "IE3",
      class_type: "Course",
      course_name: "MLE8115",
      professor: "Prof. Marin Ioana",
    },
    {
      class_day: "Vineri",
      start_hour: 3,
      end_hour: 4,
      frequency: 0,
      formation: "I3",
      class_type: "Course",
      course_name: "MLE5157",
      professor: "Lect. Filipescu Vasile",
    },
    {
      class_day: "Marți",
      start_hour: 5,
      end_hour: 6,
      frequency: 1,
      formation: "811",
      class_type: "Seminar",
      course_name: "MLE5105",
      professor: "Prof. Dinu Mariana",
    },
    {
      class_day: "Miercuri",
      start_hour: 7,
      end_hour: 8,
      frequency: 0,
      formation: "MaBD1",
      class_type: "Course",
      course_name: "MMR8001",
      professor: "Lect. Ciobanu Laura",
    },
    {
      class_day: "Joi",
      start_hour: 11,
      end_hour: 12,
      frequency: 0,
      formation: "MaSD1",
      class_type: "Course",
      course_name: "MME8110",
      professor: "Prof. Tudorache Radu",
    },
    {
      class_day: "Miercuri",
      start_hour: 9,
      end_hour: 10,
      frequency: 0,
      formation: "MaIS1",
      class_type: "Course",
      course_name: "MME8022",
      professor: "Lect. Grigorescu Adrian",
    },
    {
      class_day: "Luni",
      start_hour: 11,
      end_hour: 12,
      frequency: 0,
      formation: "MaIS1",
      class_type: "Course",
      course_name: "MME8023",
      professor: "Lect. Barbu Ana",
    },
    {
      class_day: "Joi",
      start_hour: 7,
      end_hour: 8,
      frequency: 0,
      formation: "MaICA1",
      class_type: "Course",
      course_name: "MME8059",
      professor: "Lect. Ene Gabriela",
    },
    {
      class_day: "Joi",
      start_hour: 9,
      end_hour: 10,
      frequency: 0,
      formation: "MaICA1",
      class_type: "Course",
      course_name: "MME8160",
      professor: "Prof. Stancu Mircea",
    },
  ];
};
